<a href="https://colab.research.google.com/github/rahulkumar-ml/Python-practice/blob/main/rahul_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1.calculate simple interest**

In [ ]:
principle=int(input("enter value of principal :"))
rate=int(input("enter value of rate :"))
time=int(input("enter value of time :"))
SI= (principle*rate*time)//100
print("the value of Simple Interest is :",SI)

**2.Compound Interest**

In [ ]:
principle=int(input("enter value of principal :"))
rate=int(input("enter value of rate :"))
time=int(input("enter value of time in year :"))
amount=((1+rate/100)**time)*principle
Compound_interest=amount-principle
print(Compound_interest)

**3.Area of Circle**

In [ ]:
radius=float(input("enter the value of radius :"))
pie=3.14
area = pie*(radius)**2
print(area)

enter the value of radius :5
78.5


**4. Area of Triangle**

In [ ]:
base=float(input("enter value of base:"))
height=float(input("enter value of height:"))
area=1/2*base*height
print(area)

**5.Area of Rectangle**

In [ ]:
length=float(input("enter value of length:"))
width=float(input("enter value of width:"))
area=length*width
print(area)

**6.Distance Conversion**

In [ ]:
speed=int(input("enter value of speed in km/h:"))
time=int(input("enter value of time in hour:"))
distance=speed*time
print(distance)

**7.Speed calculation**

In [ ]:
time=int(input("enter value of time in hour:"))
distance=int(input("enter value of distance in km:"))
speed= distance/time
print(speed)

**8. Body Mass Index (BMI)**

In [ ]:
weight=int(input("enter weight of person in kg :"))
height=int(input("enter height of person in meter:"))
BMI=weight/height**2
print(BMI)

**9. Temperature Conversion**

In [ ]:
temp= float(input("enter value of temoerature in celcius :"))
Fahrenheit=((9*temp)/5)+32
print("value of temoerature in Fahrenheit" ,Fahrenheit)

**10. Perimeter of Rectangle**

In [ ]:
len=float(input("provide value of length:"))
width=float(input("provide value of width:"))
Perimeter_of_rectangle=(len+width)*2
print("Perimeter of Rectangle is ",Perimeter_of_rectangle )

**1.Print all prime numbers between 1 to N**

In [ ]:
pnum=int(input("enter a value"))
if (pnum==1):
    print("neither prime nor co prime")
else:
  for i in range (2,pnum+1):
     flag=1
     for j in range(2,i):
        if(i%j==0):
          flag=0
          break
        else:
          flag=1
          j=j+1
     if(flag==1):
         print(i)




enter a value20
2
3
5
7
11
13
17
19


**2. Print the sum of all prime numbers between A to B.**

In [ ]:
pnum1=int(input("enter a value :"))
summation=0
if (pnum1==1):
    print("neither prime nor co prime")
else:
  for i in range (2,pnum1+1):
     flag=1
     for j in range(2,i):
        if(i%j==0):
          flag=0
          break
        else:
          flag=1
          j=j+1
     if(flag==1):
      summation+=i
print(summation)

enter a value :10
17






**3.Count how many numbers between 1 to N are divisible by 3 or 5**

In [ ]:
num=int(input("please provide value of n: "))
count=0
for i in range(1,num+1):
  if(i%3==0 or i%5==0):
    count+=1
print(count)

**4.Generate a multiplication table from 1 to 10 (nested loops)**

In [ ]:
multinum=int(input("please provide value of n: "))
for i in range(1,multinum+1):
  for j in range(1,multinum+1):
    print(i*j,end=" ")
  print()

**5.Check if a string is a palindrome using loop**

In [ ]:
palistring=input("please provde the string")

i=0
j=len(palistring)-1
is_palindrome=True
while (i<j):
  if(palistring[i]!=palistring[j]):
      is_palindrome=False

  i=i+1
  j=j-1
if(is_palindrome==True):
  print("This is panindrome")
else:
  print("This is not  panindrome")








please provde the stringlevel
This is panindrome


**6.Find sum of digits until the result becomes a single digit (e.g., 987 →
9+8+7 = 24 → 2+4 = 6).**

In [ ]:
;
digit=int(input("enter a digit:"))
tempdigit=digit
# lendig=len(str(tempdigit))
# lendigi=int(lendig)
sumdigit=0
while tempdigit >= 10:
  while(tempdigit>0):
    sumdigit+=tempdigit%10
    tempdigit//=10
print(sumdigit)

enter a digit:987
24


**7.Check if a number is an Armstrong number.**

In [ ]:
armnum=int(input("enter a natural number:"))
lenrum=len(str(armnum))
temparm=armnum
count=0
while (temparm>=1):
  xyz=temparm%10
  count+=xyz**lenrum
  temparm//=10
if(count==armnum):
  print("it is a armstrong number")
else:
   print("it is a  not armstrong number")



enter a digit:139
it is a  not armstrong number


**8. Generate the first N prime numbers.**

In [ ]:
prime_num=int(input("enter a digit:"))
for i in range (2,prime_num+1):
  flag=1
  for j in range (2,i):
    if(i%j==0):
      flag=0
      break
    else:
      flag=1
  if(flag==1):
    print(i)



enter a digit:20
2
3
5
7
11
13
17
19


**9.Generate the first N Fibonacci numbers using loop.**

**10.Count how many even numbers are between 1 and N**

In [ ]:
evennum=int(input("please enter a natural number :"))
addition=0
i=1
while(i<=evennum):

   if(i%2==0):
    addition +=1
    i=i+1
   else:
    i=i+1


print(addition)

please enter a natural number :20
10


**11.Count how many odd numbers are between 1 and N**

In [ ]:
oddnum=int(input("please enter a natural number :"))
oddaddition=0
i=1
while(i<=oddnum):

   if(i%2==0):

    i=i+1
   else:
    oddaddition +=1
    i=i+1
print(oddaddition)

please enter a natural number :10
5


**12.Reverse a number**

In [ ]:
revnum=input("please enter a natural number :")
# lenrev=len(revnum)
# i=lenrev-1
# while(i<=1):
#   print(revnum)
#   i=i-1
y=revnum[::-1]
print(int(y))




please enter a natural number :123
321


**13.For numbers 1 to N:
 If divisible by 3 print "Fizz"
 If divisible by 5 print "Buzz"
 If divisible by both 3 and 5 print "FizzBuzz"
 Else print number**

In [ ]:
innum= int(input("provide a number :"))
if(innum%3==0 and innum%5==0):
  print("FizzBuzz")
elif(innum%3==0):
  print("Fizz")
elif(innum%5==0):
  print("Buzz")
else:
  print(innum)

provide a number :7
7


**Print all prime numbers between 1 to N**

In [ ]:
n=int(input("provide a natural number"))
if n==1:
  print("it is neither prime or coprime")
else:
  for i in range (2,n+1):
    isprime=True
    for j in range(2,i):
      if(i%j==0):
         isprime=False
         break
  if
    isprime=True




      # else:
      #   print(j)

provide a natural number5
3
4
5
5
5


**Numpy**

**1.Create a NumPy array with values from 1 to 10.**

In [ ]:
import numpy as np
value=np.arange(1,11,1)
print(value)

[ 1  2  3  4  5  6  7  8  9 10]


**2.Create a NumPy array of five zeros.**

In [ ]:
import numpy as np
arr=np.zeros(5,dtype=int)
print(arr)

[0 0 0 0 0]


**3.Create a NumPy array of five ones.**

In [ ]:
import numpy as np
arr2=np.ones(5, dtype=int)
print(arr2)


[1 1 1 1 1]


**4.Create a NumPy array using arange() from 5 to 50 with a step of 5**

In [ ]:
import numpy as np
arr3=np.arange(5,50,5)
print(arr3)

[ 5 10 15 20 25 30 35 40 45]


**5.Create a 2D NumPy array of shape (3, 3).**

In [ ]:
import numpy as np
arra2d=np.ones((3,3))
print(arra2d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**6.Find the dimension of a given NumPy array.**

In [ ]:
import numpy as np
arra=([[1,2,3],[4,5,7],[8,9,11]])
arra2d=np.array(arra)

print(arra2d.ndim)

[[ 1  2  3]
 [ 4  5  7]
 [ 8  9 11]]
2


**7.Find the shape of a NumPy array.**

In [ ]:
import numpy as np
arra2d=np.ones((3,3))

print(arra2d.shape)

(3, 3)


**8.Access the first and last element of a NumPy array.xt**

In [ ]:
import numpy as np
a=[1,6,8,9,6,7,3,3,8,56]
first=np.array(a)
print(first[0],first[-1])

1 56


**9.Extract the second row from a 2D NumPy array.**

In [ ]:
import numpy as np
a=([[1,2,3,4][5,6,7,8][9,10,11,12]])
print(a[2,2])

<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
/tmp/ipython-input-381343288.py:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a=([[1,2,3,4][5,6,7,8][9,10,11,12]])


TypeError: list indices must be integers or slices, not tuple

**11.Add 10 to every element of a NumPy array**

In [ ]:
import numpy as np
b=[1,2,3,4,5,6,7,8,9,10]

arr4=np.array(b)
add1=arr4+10
print(add1)

[11 12 13 14 15 16 17 18 19 20]


**12.Multiply all elements of an array by 5**

In [ ]:
import numpy as np
a=[1,2,3,4,5,6,7,8,9,10]

arr3=np.array(a)
mul=arr3*5
print(mul)

[ 5 10 15 20 25 30 35 40 45 50]


**13.Find the sum of all elements in a NumPy array.**

In [ ]:
import numpy as np
a2=[1,2,3,15]
z=np.array(a)
print(z.sum())


21


**14.Find the maximum and minimum value of an array.***

In [ ]:
import numpy as np
a3=[12,8,56,758,45,89]
mini=np.array(a3)
print("maximun value of array is :",mini.max())
print("minimun value of array is :",mini.min())


maximun value of array is : 758
minimun value of array is : 8


**15.Count the total number of elements in an array.**

In [ ]:
import numpy as np
a5=[1,5,8,4,58,964,25,46]
c=np.array(a5)

print(" total number of elements in an array :",c.size)

 total number of elements in an array : 8


**17.Convert an integer array into a float array.**

In [ ]:
import numpy as np
a6=[1,5,8,4,58,964,25,46,9]
e=np.array(a5)
print(e.dtype=float)
# f=np.dtype=float(e)
# print(f)


SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (ipython-input-238399704.py, line 4)

**64 question**

**
Write a Python program to print "Hello World"**

In [ ]:
print("Hello World")

**2.Write a Python program to do arithmetical operations addition and division.t**

In [ ]:
a=int(input("provide a number"))
b=int(input("provide a number"))
sum=a+b
div=a//b
print(sum)
print(div)

provide a number5
provide a number10
15
0


**3.Write a Python program to find the area of a triangle.**

In [ ]:
base=float(input("provide a base of triangle :"))
hight=float(input("provide a height of triangle :"))
area= 1/2*(base*hight)
print(area)

**4.Write a Python program to swap two variables.**

In [ ]:
firs=float(input("enter first value :"))
sec=float(input("enter second value :"))
tem=sec
sec=firs
firs=tem
print(f"first value is {firs},second value is {sec}")

**5.Write a Python program to swap two variables without temp variable.xt**

In [ ]:
swap1=float(input("enter first value :"))
swap2=float(input("enter second value :"))
swap2,swap1=swap1,swap2
print("first value is ",swap1,"and secondvalue is" ,swap2)


enter first value :5
enter second value :2
first value is  2.0 and secondvalue is 5.0


**6.Write a Python program to convert kilometers to miles**

In [ ]:
distace=float(input("enter the total distance covered value in kilometer :"))
miles=distace*0.621371
print("total distance covered in miles is :",miles)

enter the total distance covered value in kilometer :5
total distance covered in miles is : 3.106855


**7.
Write a Python program to generate a random number**

In [ ]:
import numpy as np
print(np.random.randint(100))



1


**8.Write a Python program to convert Celsius to Fahrenheit.**

In [ ]:
temp=int(input("provide value of temprature in Celsius :"))
Fahrentemp=(temp*9/5)+32
print("Temprature in Fahrenheit is :",Fahrentemp )

provide value of temprature in Celsius :5
Temprature in Fahrenheit is : 41.0


**9.Write a Python program to display calendar.**

In [ ]:
import calendar
import datetime
year=int(input("provide value of year :" ))
month1=int(input("provide value of month :" ))
print(calendar.month(year,month1))

provide value of year :2026
provide value of month :3
     March 2026
Mo Tu We Th Fr Sa Su
                   1
 2  3  4  5  6  7  8
 9 10 11 12 13 14 15
16 17 18 19 20 21 22
23 24 25 26 27 28 29
30 31



**10.Write a Python Program to Check if a Number is Positive, Negative or Zero**

In [ ]:
Number=float(input("enter a number  :"))
if(Number>0):
  print("It is Positive number")
elif(Number==0):
   print("It is Zero")
else:
   print("It is Negative number")


enter a number  :-96
It is Negative number


**11.Write a Python Program to Check if a Number is Odd or Even.**

In [ ]:
evenodd=float(input("enter a number  :"))
if(evenodd%2==0):
   print("It is Even number")
else:
  print("It is odd number")


enter a number  :59
It is odd number


**12.
Write a Python Program to Check Leap Year**

In [ ]:
year=int(input("enter year you want to check leap year or not"))
if (year%4==0 and year%100!=0):
  print("leap year")
elif(year%100==0 and year%400==0):
  print("leap year")
else:
  print("not a leap year")

enter year you want to check leap year or not400
leap year


**13.
Write a Python Program to Check Prime Number.**

In [ ]:
Numberprime=int(input("enter a natural number"))

if(Numberprime==1):
  print(Numberprime,"is neither Prime nor CoPrime Number")
else:
  flag=True
  for i in range(2,Numberprime):
    if(Numberprime%i==0):
      flag=False
      break

    else:
      flag=True
      i=i+1
  if (flag==True):
    print("Number",Numberprime," is Prime Number ")
  else:
    print(Numberprime,"is not Prime Number")




enter a natural number1
1 isneither Prime not CoPrime Number


**14.Write a Python Program to Print all Prime Numbers in an Interval of 1-10.**

In [ ]:


for i in range(2,11):
  flag=True
  for j in range(2,i):
    if(i%j==0):
      flag=False
      break
    else:
      flag=True
      j=j+1
  if(flag==True):
    print(i)


2
3
5
7


**15.
Write a Python Program to Find the Factorial of a Number.**

In [ ]:
Factnum=int(input("enter a natural number"))
mul=1
for i in range(Factnum,0,-1):
  mul*=i
print(mul)





enter a natural number4
24


**16.
Write a Python Program to Display the multiplication Table.**

In [ ]:
TableNum=int(input("enter a natural number"))
for i in range (1,11):
  print(TableNum*i)

enter a natural number20
20
40
60
80
100
120
140
160
180
200


**17.
Write a Python Program to Find Armstrong Number in an Interval.**

In [ ]:
lower=int(input("provide lower limit :"))
upper=int(input("provide upper limit :"))
for num in range(lower,upper+1):
  length=len(str(num))
  var1=num
  sum=0
  while(var1>0):
    Num5=var1%10
    sum+=Num5**length
    var1//=10
  if(num==sum):
    print(num)



provide upper limit :1000
provide lower limit :100
153
370
371
407


**18.
Write a Python Program to Find the Sum of Natural Numbers.**

In [ ]:
# NaturSum=int(input("enter a natural number"))
# sum2=0
# for i in range(1,NaturSum+1):
#   sum2+=i
# print(sum2)
def NaturSum(n):
  add=0
  for i in range(1,n+1):
    add+=i
  return add
Sum=int(input("enter a natural number"))
print(NaturSum(Sum))


enter a natural number100
5050


**19,20,21,22.Write a Python Program to Convert Decimal to Binary, Octal and Hexadecimal.**

In [ ]:
Decinum=int(input("enter a Decimal number"))
# to convert to binary
temp=Decinum

l1=[]
while(temp>0):
  rem=temp%2
  l1.append(rem)
  temp//=2
print(l1[::-1])




enter a Decimal number27
[1, 1, 0, 1, 1]


**convert a decimal number to octal**

In [ ]:
Decinum1=int(input("enter a Decimal number"))
# to convert to octal
oct1=Decinum1
l2=[]
while(oct1>0):
  rem1=oct1%8
  l2.append(rem1)
  oct1//=8
print(l2[::-1])

enter a Decimal number27
[3, 3]


**convert a decimal number to hexadecimal**

In [ ]:
Decinum2=int(input("enter a Decimal number"))
li8=[0,1,2,3,4,5,6,7,8,9,"A","B","C","D","E","F"]
var5=Decinum2
list3=[]
while(var5>0):
  rem2=var5%16
  list3.append(rem2)
  var5//=16

list3.reverse()
lenueh=len(str(list3))
for i in list3:
  print(li8[i] ,end="")



enter a Decimal number27
1B

**25.Write a Python Program to find largest element in an array.**

In [ ]:
import numpy as np
aray=[1,6,8,9,6,7,3,3,8,56]
fst=np.array(aray)
maximumvalue=fst.max()
print(maximumvalue)


56


**26.Write a Python Program for array rotation.**

In [ ]:
import numpy as np
aryay=[1,6,8,9,6,7,3,3,8,56]
fist=np.array(aryay)
# rotate=np.reverse(fist)
print(fist[::-1])

[56  8  3  3  7  6  9  8  6  1]


** Check Prime Number using function**

In [ ]:
def is_prime(n):
  Flag= True
  if(n==1):
    return "not a prime nor co prime"
  else:
   for j in range(2,n):
    if(n%j==0):
      Flag= False
      break
    else:
      Flag= True
      j=j+1
  if( Flag== True):
    return "Prime",n
  else:
    return"Not Prime",n


for i in range(1,21):
  x=is_prime(i)
  print(x)


**leap year using function**

In [ ]:
def leap_year(n):
  for i in range(len(n)):

    yr=n[i]

    if(yr%4==0 and yr%100!=0) or (yr%100==0 and yr%400==0):
      print("True")
    else:
       print("false")

test_data = [1900, 2000, 2016, 1987]
leap_year(test_data)

**checking Prime or not  using function**

In [ ]:
def is_prime(n):
  Flag= True
  if(n==1):
    return "not a prime nor co prime"
  else:
   for j in range(2,n):
    if(n%j==0):
      Flag= False
      break
    else:
      Flag= True
      j=j+1
  if( Flag== True):
    return "Prime",n
  else:
    return"Not Prime",n


for i in range(1,21):
  x=is_prime(i)
  print(x)

**Checking triangle**

In [ ]:
def is_triangle(a,b,c):
  if(a+b>c)and (b+c>a)and (c+a>b):
    return True
  else:
    return False
one=int(input(" enter len of 1st side triangle"))
two=int(input(" enter len of 2nd side triangle"))
three=int(input(" enter len of 3rdside triangle"))
print(is_triangle(one,two,three))

**factorial of a number**

In [ ]:
def fact(num18):
  if num18<0:
   return (None)
  elif num18==0:
    return(1)
  else:
    mul=1
    for i in range(1,num18+1):
      mul*=i
    return(mul)

num18=int(input("enter a number to which we have to find factorial :"))
x=fact(num18)
print(x)

enter a number to which we have to find factorial :6
720


**fabonachi number**

In [1]:
def fab(nn):
  if(nn<1):
    return None
  elif(nn<3):
    return 1
  ele1=1
  ele2=1
  for i in range(3,nn+1):
    sum=0
    xy=ele1+ele2
    sum+=xy
    ele1=ele2
    ele2=sum
  return sum
xz=int(input("enter a number :"))
print(fab(nn=xz))




enter a number :12
144


In [ ]:
skladhf'ljas;f
sdjkhfkjdsk'